export default {
  ID_ERROR: 'ID_ERROR',
  PASSWORD_ERROR: 'PASSWORD_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  SET_AUTH: 'SET_AUTH',
  GET_AUTH: 'GET_AUTH',
  REMOVE_AUTH: 'REMOVE_AUTH',
  REGISTER_ID_ERROR: 'REGISTER_ID_ERROR',
  REGISTER_PASSWORD_ERROR: 'REGISTER_PASSWORD_ERROR',
  REGISTER_MAIL_ERROR: 'REGISTER_MAIL_ERROR',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER: 'REGISTER',
  OPEN_MENU: 'OPEN_MENU'
}
